
#key names
PIXELS_NAME = "pixels"
TOTAL_NAME = "total_donate"
RESPONSE_NAME = "text_response"
ALPHA_NAME = "alpha"
INVOICE_NODE = "invoice"
HISTORY_NODE = "history"
INVOICE_HISTORY_NODE = "invoice_history"
TIME_NAME = "Time"
HEARTBEAT_TIME_NAME = "heartbeat_time"
ART_NAME = "art"
Q_NODE = "queue"
DUMP_NAME = "canvas_dump"
RESOLVE_TIME = "resolved_at"
RESOLVE_HEARTBEAT_TIME = "resolved_heartbeat_time"
ALPHA_INDEX_NODE = "alphas"